# -*- coding: utf-8 -*-
"""Inject the worked UCC examples from docs/domain-examples.json into the player.

Three targeted edits, each idempotent and each confined to its own region of
course/index.html:

  1. a "domainExample" key on each module object, immediately before its
     "devLens" key  -- inside `const MODS = [` ... `];\\n\\nconst TRACK_META`
  2. the M00 domain primer, as the first entry of M00's "sections" array
  3. the UCC_GLOSSARY const, regenerated from docs/ucc-corpus.json
     -- inside the `/* UCC:START */` ... `/* UCC:END */` region

Modelled on inject_devlens.py: targeted insertion rather than re-serialisation,
so the diff stays small and the file's existing indentation and module
separators survive.

The generated walkthrough bundle between WT:START and WT:END is never touched,
and neither is the `];\\n\\nconst TRACK_META` marker that inject_devlens.py
anchors on -- the glossary region sits after TRACK_META for exactly that reason.

Run from the repo root:

    python scripts/inject_domain_examples.py            # inject / refresh
    python scripts/inject_domain_examples.py --check    # report only, change nothing
"""
import json
import re
import sys
from html.parser import HTMLParser

HTML = "course/index.html"
EXAMPLES = "docs/domain-examples.json"
CORPUS = "docs/ucc-corpus.json"
DOMAIN_MD = "labs/DOMAIN.md"

MODS_START = "const MODS = ["
MODS_END = "];\n\nconst TRACK_META"

# The primer is keyed on its title, which is therefore load-bearing: change it
# here and in docs/domain-examples.json together or the strip stops matching and
# a re-run appends a second primer.
PRIMER_TITLE = "The Filing on Your Desk"

GLOSSARY_RE = re.compile(r"/\* UCC:START.*?/\* UCC:END \*/", re.S)


def esc(value):
    """JSON-encode a string for embedding in the inline MODS literal."""
    # The </script> guard is required because MODS lives inside a <script>
    # block (CLAUDE.md checklist rule 12).
    return json.dumps(value, ensure_ascii=False).replace("</script>", "<\\/script>")


def build_example(indent, ex):
    pad = indent + "  "
    return (
        '%s"domainExample": {\n'
        '%s"title": %s,\n'
        '%s"body": %s,\n'
        '%s"caption": %s\n'
        '%s},\n'
    ) % (indent, pad, esc(ex["title"]), pad, esc(ex["body"]),
         pad, esc(ex.get("caption", "")), indent)


def build_primer(indent, primer):
    # "primer": true is what showModule() hoists on, so the primer renders above
    # the worked example instead of three blocks below it. A marker rather than a
    # title match, so the player never has to hardcode PRIMER_TITLE.
    pad = indent + "  "
    return (
        '%s{\n'
        '%s"type": "content",\n'
        '%s"primer": true,\n'
        '%s"title": %s,\n'
        '%s"body": %s\n'
        '%s},\n'
    ) % (indent, pad, pad, pad, esc(primer["title"]), pad, esc(primer["body"]), indent)


def build_glossary(corpus):
    terms = json.dumps(corpus["glossary"], ensure_ascii=False, indent=2)
    terms = terms.replace("</script>", "<\\/script>")
    return (
        "/* UCC:START — generated by scripts/inject_domain_examples.py from "
        "docs/ucc-corpus.json.\n"
        "   Do not hand-edit; edit the corpus and re-run. Kept outside the MODS array so\n"
        "   inject_devlens.py's `];\\n\\nconst TRACK_META` anchor stays intact, and far from\n"
        "   the WT:START/WT:END walkthrough bundle. */\n"
        "const UCC_GLOSSARY = %s;\n"
        "/* UCC:END */"
    ) % terms


class _PrimerToMarkdown(HTMLParser):
    """Render the primer's restricted HTML as Markdown for labs/DOMAIN.md.

    The worked-example vocabulary is closed and machine-checked
    (scripts/check-module.js), so this only has to handle the tags the primer
    actually uses -- and it raises on anything else rather than silently
    dropping content, so widening the primer fails the build instead of
    quietly shipping a half-rendered reference.
    """

    INLINE = {"strong": "**", "em": "_", "code": "`"}
    LEAVES = {"ue-rec-h", "ue-fk", "ue-fv", "ue-ann", "ue-note"}

    def __init__(self):
        HTMLParser.__init__(self)
        self.blocks = []
        self.stack = []
        self.buf = None
        self.rec = None
        self.row = None

    # -- helpers -------------------------------------------------------
    def _text(self):
        out = " ".join("".join(self.buf).split())
        self.buf = None
        return out

    def handle_starttag(self, tag, attrs):
        cls = dict(attrs).get("class", "")
        self.stack.append((tag, cls))
        if tag == "p":
            self.buf = []
        elif tag == "div" and cls == "ue-rec":
            self.rec = {"head": "", "rows": []}
        elif tag == "div" and cls == "ue-f":
            self.row = {"ue-fk": "", "ue-fv": "", "ue-ann": ""}
        elif cls in self.LEAVES:
            self.buf = []
        elif cls == "ue-mark" or tag in self.INLINE:
            if self.buf is None:
                raise ValueError("inline <%s> outside a text block" % tag)
            self.buf.append("**" if cls == "ue-mark" else self.INLINE[tag])
        elif tag == "br":
            self.stack.pop()
        else:
            raise ValueError("primer uses unsupported <%s class=%r>" % (tag, cls))

    def handle_endtag(self, tag):
        if not self.stack:
            return
        _, cls = self.stack.pop()
        if tag == "p":
            self.blocks.append(self._text())
        elif tag == "div" and cls == "ue-rec":
            self.blocks.append(self._record(self.rec))
            self.rec = None
        elif tag == "div" and cls == "ue-f":
            self.rec["rows"].append(self.row)
            self.row = None
        elif cls == "ue-rec-h":
            self.rec["head"] = self._text()
        elif cls in ("ue-fk", "ue-fv", "ue-ann"):
            self.row[cls] = self._text()
        elif cls == "ue-note":
            note = self._text()
            self.blocks.append("\n".join("> " + l for l in _wrap(note)))
        elif cls == "ue-mark" or tag in self.INLINE:
            self.buf.append("**" if cls == "ue-mark" else self.INLINE[tag])

    def handle_data(self, data):
        if self.buf is not None:
            self.buf.append(data)
        elif data.strip():
            raise ValueError("stray text in primer: %r" % data[:40])

    @staticmethod
    def _record(rec):
        out = ["**%s**" % rec["head"], ""]
        for r in rec["rows"]:
            out.append("- **%s** — %s" % (r["ue-fk"], r["ue-fv"]))
            if r["ue-ann"]:
                out.append("  _%s_" % r["ue-ann"])
        return "\n".join(out)


def _wrap(text, width=92):
    """Soft-wrap a paragraph so the generated Markdown reads in a plain editor."""
    lines, line = [], ""
    for word in text.split():
        if line and len(line) + 1 + len(word) > width:
            lines.append(line)
            line = word
        else:
            line = (line + " " + word).strip()
    if line:
        lines.append(line)
    return lines or [""]


def build_domain_md(primer, corpus):
    """One page a lab reader can keep open: what a filing is, who the cast is,
    what each of the ten filings is for, and every term the course uses.

    The per-filing `teaches` prose and `class` labels are authored in the corpus
    and rendered nowhere else -- this is the only place a learner ever sees them.
    """
    p = _PrimerToMarkdown()
    p.feed(primer["body"])
    p.close()

    L = [
        "# The UCC domain, in one page",
        "",
        "<!-- Generated by scripts/inject_domain_examples.py from docs/ucc-corpus.json and",
        "     docs/domain-examples.json. Do not hand-edit; edit those and re-run. -->",
        "",
        "The labs process commercial lien filings. You do not need to know the domain to do",
        "them, but you do need to know what the fields mean — this page is the whole of it.",
        "The course player carries the same material: the primer opens M00, and the glossary",
        "sits in the nav drawer, reachable from every module.",
        "",
        "---",
        "",
        "## %s" % primer["title"],
        "",
    ]
    for b in p.blocks:
        # records and notes are already multi-line; wrap plain paragraphs
        if "\n" in b or b.startswith(">"):
            L.append(b)
        else:
            L += _wrap(b)
        L.append("")

    cast = corpus["cast"]
    L += [
        "",
        "---",
        "",
        "## The cast",
        "",
        "The same companies recur across every module and lab, so a filing you meet in M20 is",
        "one you already know.",
        "",
        "| | |",
        "|---|---|",
        "| **Debtor** | %s |" % cast["primary_debtor"],
        "| **Secured party** | %s |" % cast["primary_secured_party"],
        "| **Shared address** | %s |" % cast["shared_address"],
        "",
        cast["note"],
        "",
        "---",
        "",
        "## The ten filings",
        "",
        "Every filing id used in the course resolves to one of these. Each exists to teach one",
        "specific failure.",
        "",
        "| Filing | Type | Status | Edge case | What it is for |",
        "|---|---|---|---|---|",
    ]
    for f in corpus["filings"]:
        L.append("| `%s` | %s | %s | %s | %s |" % (
            f["id"], f["type"], f.get("status", "—"),
            f["class"], f["teaches"].replace("|", "\|")))

    L += ["", "---", "", "## Glossary", ""]
    for g in corpus["glossary"]:
        L.append("**%s** — %s" % (g["term"], g["short"]))
        if g.get("long"):
            L += [""] + ["> " + l for l in _wrap(g["long"])]
        L.append("")

    return "\n".join(L).rstrip() + "\n"


def main():
    check_only = "--check" in sys.argv

    with open(EXAMPLES, encoding="utf-8") as f:
        doc = json.load(f)
    with open(CORPUS, encoding="utf-8") as f:
        corpus = json.load(f)

    primer = doc.get("_primer")
    examples = {k: v for k, v in doc.items() if not k.startswith("_")}

    with open(HTML, encoding="utf-8", newline="") as f:
        raw = f.read()
    newline = "\r\n" if "\r\n" in raw else "\n"
    src = raw.replace("\r\n", "\n")

    start = src.index(MODS_START)
    end = src.index(MODS_END, start)
    head, mods, tail = src[:start], src[start:end], src[end:]

    # ---------------------------------------------------------- domainExample
    existing = len(re.findall(r'^\s*"domainExample": \{$', mods, re.M))
    mods = re.sub(
        r'^[ \t]*"domainExample": \{\n'
        r'[ \t]*"title": .*\n'
        r'[ \t]*"body": .*\n'
        r'[ \t]*"caption": .*\n'
        r'[ \t]*\},\n',
        "", mods, flags=re.M)

    injected = 0
    for mid in sorted(examples):
        m = re.search(r'"id": "%s"' % re.escape(mid), mods)
        if not m:
            print("  ! %s: no module object found in MODS" % mid)
            continue

        dl = re.search(r'^([ \t]*)"devLens":', mods[m.end():], re.M)
        if not dl:
            print("  ! %s: no devLens key found to anchor on" % mid)
            continue

        # The anchor must belong to this module, not the next one.
        nxt = re.search(r'"id": "M\d\d"', mods[m.end():])
        if nxt and nxt.start() < dl.start():
            print("  ! %s: devLens anchor crosses into the next module" % mid)
            continue

        at = m.end() + dl.start()
        mods = mods[:at] + build_example(dl.group(1), examples[mid]) + mods[at:]
        injected += 1

    print("%d module(s) already carried a worked example; injecting %d"
          % (existing, injected))

    if injected != len(examples):
        print("ERROR: expected %d, injected %d" % (len(examples), injected))
        return 1

    # ----------------------------------------------------------- M00 primer
    primed = 0
    if primer:
        had = len(re.findall(r'"title": %s' % re.escape(esc(primer["title"])), mods))
        mods = re.sub(
            r'^[ \t]*\{\n'
            r'[ \t]*"type": "content",\n'
            r'(?:[ \t]*"primer": true,\n)?'   # also strips pre-marker primers
            r'[ \t]*"title": %s,\n'
            r'[ \t]*"body": .*\n'
            r'[ \t]*\},\n' % re.escape(esc(primer["title"])),
            "", mods, flags=re.M)

        m = re.search(r'"id": "M00"', mods)
        if not m:
            print("  ! primer: M00 not found")
            return 1
        sec = re.search(r'^([ \t]*)"sections": \[\n', mods[m.end():], re.M)
        if not sec:
            print("  ! primer: M00 has no sections array")
            return 1
        nxt = re.search(r'"id": "M\d\d"', mods[m.end():])
        if nxt and nxt.start() < sec.start():
            print("  ! primer: sections anchor crosses into the next module")
            return 1

        at = m.end() + sec.end()
        mods = mods[:at] + build_primer(sec.group(1) + "  ", primer) + mods[at:]
        primed = 1
        print("primer: %d already present; injecting 1 into M00 sections[0]" % had)

    # -------------------------------------------------------------- glossary
    src = head + mods + tail
    if not GLOSSARY_RE.search(src):
        print("ERROR: no /* UCC:START ... UCC:END */ region in %s" % HTML)
        return 1
    src = GLOSSARY_RE.sub(lambda _: build_glossary(corpus), src, count=1)
    print("glossary: %d terms written into UCC_GLOSSARY" % len(corpus["glossary"]))

    # ------------------------------------------------------- labs/DOMAIN.md
    # The labs are standalone Markdown on GitHub with no player around them, so
    # they get the same primer, cast and glossary as a page they can keep open.
    domain_md = build_domain_md(primer, corpus) if primer else None
    if domain_md:
        print("domain reference: %d filings, %d terms -> %s"
              % (len(corpus["filings"]), len(corpus["glossary"]), DOMAIN_MD))

    if check_only:
        print("--check: no file written")
        return 0

    with open(HTML, "w", encoding="utf-8", newline="") as f:
        f.write(src.replace("\n", newline))
    if domain_md:
        with open(DOMAIN_MD, "w", encoding="utf-8", newline="\n") as f:
            f.write(domain_md)
    print("wrote %s (%s line endings) — %d examples, %d primer"
          % (HTML, "CRLF" if newline == "\r\n" else "LF", injected, primed))
    return 0


if __name__ == "__main__":
    sys.exit(main())
